development:
  adapter: sqlite3
  database: bytely_development

test:
  adapter: sqlite3
  database: bytely_test

production:
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
